# Generated by Django 5.1.3 on 2024-11-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='daily_log',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('mental', models.CharField(max_length=2)),
                ('weight', models.CharField(blank=True, max_length=5)),
                ('video', models.CharField(blank=True, max_length=25)),
            ],
        ),
    ]
